server:
  port: 8080
  servlet:
    context-path: /plantinha

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./plantinha
    username: root
    password: root

  h2:
    console:
      enabled: true
      path: /db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect